"""empty message

Revision ID: 576abc62c7fb
Revises: 8b37ca5f5aa7
Create Date: 2023-08-24 18:27:15.009396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576abc62c7fb'
down_revision = '8b37ca5f5aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))  # Make it nullable initially
        batch_op.add_column(sa.Column('img_url', sa.String(length=500), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('image_url')

    # Populate 'id' for existing rows here, if needed. For example:
    # op.execute("UPDATE pokemon SET id = 1 WHERE name = 'Bulbasaur'")
    # op.execute("UPDATE pokemon SET id = 2 WHERE name = 'Ivysaur'")
    # op.execute("UPDATE pokemon SET id = 3 WHERE name = 'Venusaur'")
    # op.execute("UPDATE pokemon SET id = 4 WHERE name = 'Charmander'")
    # op.execute("UPDATE pokemon SET id = 5 WHERE name = 'Charmeleon'")
    # op.execute("UPDATE pokemon SET id = 6 WHERE name = 'Charizard'")
    # op.execute("UPDATE pokemon SET id = 7 WHERE name = 'Squirtle'")
    # op.execute("UPDATE pokemon SET id = 8 WHERE name = 'Wartortle'")
    # op.execute("UPDATE pokemon SET id = 9 WHERE name = 'Blastoise'")
    # op.execute("UPDATE pokemon SET id = 10 WHERE name = 'Caterpie'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pokemon_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_pokemon_pokemon_name_fkey', 'pokemon', ['pokemon_name'], ['name'])
        batch_op.drop_column('pokemon_id')

    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('img_url')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
